version: '3'

tasks:
  CI:
    deps:
      - test
      - check
      - bench-dryrun

  CI:nobench:
    deps:
      - test
      - check

  test:
    deps:
      - test:doc
      - test:lib
      - test:examples
  
  check:
    deps:
      - check:lib
      - check:examples
  
  bench:
    deps:
      - bench:all

  bench-dryrun:
    deps:
      - bench:dryrun

  ##### test #####

  test:doc:
    cmds:
      - cargo test --doc --features DEBUG
  
  test:lib:
    cmds:
      - cargo test --lib --features DEBUG

  test:examples:
    dir: examples
    cmds:
      - cargo run --example readme
      - cargo run --example validator
      - cargo run --example various_users

  ##### check #####

  check:lib:
    cmds:
      - cargo check
  
  check:examples:
    dir: examples
    cmds:
      - cargo check --examples

  ##### bench #####

  bench:all:
    cmds:
      - cargo bench

  bench:dryrun:
    cmds:
      - cargo bench --no-run
