version: '3'

vars:
  maybe_nightly: { sh: cargo version | grep -q 'nightly' && echo 'nightly' || echo ''  }

tasks:
  CI:
    deps:
      - test
      - check
      - bench-dryrun

  test:
    deps:
      - test:doc
      - test:lib
      - test:examples
  
  check:
    deps:
      - check:fmt
      - check:clippy
  
  bench:
    status:
      - '[ "{{.maybe_nightly}}" != "nightly" ]' # skip if not nightly
    cmds:
      - task: bench:all

  bench-dryrun:
    status:
      - '[ "{{.maybe_nightly}}" != "nightly" ]' # skip if not nightly
    cmds:
      - task: bench:dryrun
  
  ###########################################################################

  ##### test #####

  test:doc:
    dir: ./serdev
    cmds:
      - cargo test --doc
  
  test:lib:
    cmds:
      - cargo test --lib

  test:examples:
    dir: examples
    cmds:
      - for file in `ls ./examples`; do cargo run --example "${file%.*}"; done
      - cd reexport && cargo run

  ##### check #####
  
  check:fmt:
    cmds:
      - cargo fmt --all --check

  check:clippy:
    vars:
      targets: # all, but skip benches on non-nightly
        sh: |
          if [ {{.maybe_nightly}} = "nightly" ]; then
            echo "--all-targets"
          else
            echo "--lib --tests --examples"
          fi          
    cmds:
      - cargo clippy {{.targets}} -- --deny warnings
      - cd examples && cargo clippy --examples -- --deny warnings
  
  ##### bench #####

  bench:all:
    cmds:
      - cargo bench

  bench:dryrun:
    cmds:
      - cargo bench --no-run
