version: '3'

tasks:
  CI:
    deps:
      - test
      - check
      - bench-dryrun

  CI:nobench:
    deps:
      - test
      - check

  test:
    deps:
      - test:doc
      - test:lib
      - test:examples
  
  check:
    deps:
      - check:fmt
      - check:clippy
  
  bench:
    deps:
      - bench:all

  bench-dryrun:
    deps:
      - bench:dryrun

  ##### test #####

  test:doc:
    cmds:
      - cargo test --doc
  
  test:lib:
    cmds:
      - cargo test --lib

  test:examples:
    dir: examples
    cmds:
      - cargo run --example method_path
      - cargo run --example closure
      - cargo run --example validator
      - cargo run --example various_users
      - cd reexport && cargo run

  ##### check #####
  
  check:fmt:
    cmds:
      - cargo fmt --all --check

  check:clippy:
    cmds:
      - cargo clippy --all-targets -- --deny warnings
      - cd examples && cargo clippy --examples -- --deny warnings
  
  ##### bench #####

  bench:all:
    cmds:
      - cargo bench

  bench:dryrun:
    cmds:
      - cargo bench --no-run
