version: '3'

tasks:
  CI:
    deps:
      - test
      - check

  test:
    deps:
      - test:doc
      - test:lib
      - test:examples
  
  check:
    deps:
      - check:lib
      - check:examples

  ##### test #####

  test:doc:
    cmds:
      - cargo test --doc --features DEBUG
  
  test:lib:
    cmds:
      - cargo test --lib --features DEBUG

  test:examples:
    dir: examples
    cmds:
      - cargo test --examples

  ##### check #####

  check:lib:
    cmds:
      - cargo check
  
  check:examples:
    dir: examples
    cmds:
      - cargo check --examples
