[workspace]
resolver = "2"
members  = ["."]
exclude  = ["reexport"]

[package]
name    = "examples"
version = "0.0.0"
edition = "2021"

[dev-dependencies]
serdev     = { path = "../serdev" }
serde_json = { version = "1.0" }
validator  = { version = "0.16", features = ["derive"] }