[package]
name          = "serdev_derive"
description   = "proc macros for SerdeV - Serde with Validation"
documentation = "https://docs.rs/serdev_derive"
version       = { workspace = true }
edition       = { workspace = true }
authors       = { workspace = true }
homepage      = { workspace = true }
repository    = { workspace = true }
readme        = { workspace = true }
keywords      = { workspace = true }
categories    = { workspace = true }
license       = { workspace = true }

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0" }
quote       = { version = "1.0" }
syn         = { version = "2.0", features = ["full"] }
