[workspace]
resolver = "2"
members  = ["reexporter", "."]

[package]
name    = "user"
version = "0.0.0"
edition = "2021"

[dependencies]
reexporter = { path = "./reexporter" }
serde_json = { version = "1.0" }