name: CI
on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  CI:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain: ['stable', 'nightly']

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup Rust
        run: |
          rustup update
          rustup default ${{ matrix.toolchain }}
          rustup component add rustfmt clippy
          
      - uses: go-task/setup-task@0ab1b2a65bc55236a3bc64cde78f80e20e8885c2 # v1.0.0
        with:
          version: 3.45.5

      - name: Run task
        if: ${{ matrix.toolchain == 'stable' }} # temporary WORKAROUND for link error on nightly
        run: task CI
        